const SOURCES_KEY = "hacker-librarian:sources";
const CLAIMS_KEY = "hacker-librarian:claims";
const SETTINGS_KEY = "hacker-librarian:settings";

const DEFAULT_SETTINGS = {
  routerEndpoint: "https://router-api.0g.ai/v1",
  model: "",
  apiKey: "",
  persistApiKey: false,
};

function readJson(key, fallback) {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : fallback;
  } catch {
    return fallback;
  }
}

function writeJson(key, value) {
  localStorage.setItem(key, JSON.stringify(value));
}

export function loadSources() {
  return readJson(SOURCES_KEY, []);
}

export function saveSources(sources) {
  writeJson(SOURCES_KEY, sources);
}

export function loadClaims() {
  return readJson(CLAIMS_KEY, []);
}

export function saveClaims(claims) {
  writeJson(CLAIMS_KEY, claims);
}

export function loadSettings() {
  const saved = readJson(SETTINGS_KEY, DEFAULT_SETTINGS);
  return {...DEFAULT_SETTINGS, ...saved, apiKey: saved.persistApiKey ? saved.apiKey || "" : ""};
}

export function saveSettings(settings) {
  writeJson(SETTINGS_KEY, {
    routerEndpoint: settings.routerEndpoint || DEFAULT_SETTINGS.routerEndpoint,
    model: settings.model || "",
    apiKey: settings.persistApiKey ? settings.apiKey || "" : "",
    persistApiKey: Boolean(settings.persistApiKey),
  });
}

export function clearLibrary() {
  localStorage.removeItem(SOURCES_KEY);
  localStorage.removeItem(CLAIMS_KEY);
}

export function createSource({title, url, content}) {
  const normalizedContent = content.trim();
  const id = `src_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  return {
    id,
    title: title.trim() || new URL(url).hostname,
    url,
    source_type: "user_supplied_url",
    acquired_at: new Date().toISOString(),
    summary: summarize(normalizedContent),
    content: normalizedContent,
    quality: scoreSource({url, content: normalizedContent}),
  };
}

export function searchSources(sources, question, limit = 5) {
  const terms = tokenize(question);
  return sources
    .map((source) => ({source, rank: rankSource(source, terms)}))
    .filter((item) => item.rank > 0)
    .sort((a, b) => b.rank - a.rank || (b.source.quality?.score || 0) - (a.source.quality?.score || 0))
    .slice(0, limit)
    .map(({source}) => ({...source, excerpt: excerptFor(source.content, terms)}));
}

export async function askWithRouter({settings, question, evidence}) {
  if (!settings.routerEndpoint || !settings.apiKey || !settings.model) {
    return localAnswer(question, evidence);
  }

  const response = await fetch(`${settings.routerEndpoint.replace(/\/$/, "")}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${settings.apiKey}`,
    },
    body: JSON.stringify({
      model: settings.model,
      messages: [
        {
          role: "system",
          content:
            "You are Hacker Librarian. Answer only from the provided sources. Cite source ids in brackets. State uncertainty when evidence is thin.",
        },
        {
          role: "user",
          content: `${question}\n\nSources:\n${JSON.stringify(evidence, null, 2)}`,
        },
      ],
    }),
  });

  if (!response.ok) {
    throw new Error(await response.text());
  }

  const payload = await response.json();
  return {
    answer: payload.choices?.[0]?.message?.content || "No answer returned by the selected 0G Router model.",
    citations: evidence.map((item) => item.id),
    evidence,
    uncertainty: "Generated by the user's configured 0G Router endpoint.",
    provider: "0g-router",
  };
}

export function localAnswer(question, evidence) {
  if (!evidence.length) {
    return {
      answer: "No matching local sources were found in this browser library.",
      citations: [],
      evidence: [],
      uncertainty: "Add source text first, or configure 0G Router for model-assisted answers.",
      provider: "local",
    };
  }

  const citations = evidence.map((item) => item.id);
  return {
    answer: `Local evidence search found ${evidence.length} relevant source(s) for "${question}". Review the excerpts below before treating this as an answer. ${citations.map((id) => `[${id}]`).join(" ")}`,
    citations,
    evidence,
    uncertainty: "This is a local browser fallback, not model reasoning. Configure a 0G Router endpoint and model for generated answers.",
    provider: "local",
  };
}

export function extractClaims(sources) {
  return sources.flatMap((source) =>
    source.content
      .split(/[.!?]\s+/)
      .map((part) => part.trim())
      .filter((part) => part.length > 60)
      .slice(0, 3)
      .map((claim, index) => ({
        id: `${source.id}_claim_${index + 1}`,
        claim,
        status: "needs_review",
        confidence: 0.45,
        source_id: source.id,
      })),
  );
}

function scoreSource({url, content}) {
  const reasons = [];
  let score = 35;
  if (url.startsWith("https://")) {
    score += 15;
    reasons.push("HTTPS source URL.");
  }
  if (content.length > 500) {
    score += 20;
    reasons.push("Substantial user-provided text.");
  }
  if (/\b(author|published|doi|archive|source|evidence)\b/i.test(content)) {
    score += 10;
    reasons.push("Text includes provenance-like terms.");
  }
  reasons.push("Stored only in this browser unless the user exports or syncs it.");
  return {
    score: Math.min(score, 90),
    tier: score >= 70 ? "usable source, verify important claims" : "needs more provenance",
    reasons,
    needs_verification: true,
  };
}

function summarize(content) {
  const first = content.replace(/\s+/g, " ").trim().slice(0, 220);
  return first ? `${first}${content.length > 220 ? "..." : ""}` : "No source text yet.";
}

function tokenize(text) {
  return (text.toLowerCase().match(/[a-z0-9_]{3,}/g) || []).filter(Boolean);
}

function rankSource(source, terms) {
  const haystack = `${source.title} ${source.url} ${source.content}`.toLowerCase();
  return terms.reduce((score, term) => score + (haystack.includes(term) ? 1 : 0), 0);
}

function excerptFor(content, terms) {
  const compact = content.replace(/\s+/g, " ").trim();
  const lower = compact.toLowerCase();
  const index = terms.map((term) => lower.indexOf(term)).find((pos) => pos >= 0) ?? 0;
  const start = Math.max(0, index - 120);
  return compact.slice(start, start + 360);
}
